### ISSUE TITLE
Add dependensies to build

### ISSUE THREAD

**Issue by falkowich** [falkowich/gvm10-docker#10]
sudo apt install  gettext python-polib git

**Comment by cyrinux** [comment]
Hi, could you please also dependencies to be able to generate the pdf?
There is some infos here if needed https://www.linuxincluded.com/installing-openvas-on-centos-7/ in the "Configuring PDF Reports" part.
Thanks!

**Comment by falkowich** [comment]
Hi, I will look in to that "ASAP" :tm: :)
Well atleast soon..

And thanks for the suggestions!

--
Regards Falk

**Comment by falkowich** [comment]
This is now added in upcoming gvm10:latest images
It should now work in -dev images.

**Comment by falkowich** [comment]
This is now added to latest stable images on github.
https://github.com/falkowich/gvm10-docker/commit/7d13569c941313c10b1aefdff9768cc0ced6b41d
