### ISSUE TITLE
【gvm10:psql  】 postgres CPU 100%

### ISSUE THREAD

**Issue by xjx363631317** [falkowich/gvm10-docker#11]
after run psql's container , the postgres use 100%CPU . last for a long time

**Comment by falkowich** [comment]
Hi,

Did you get anywhere with this?
Sorry that I haven't answered before.. 
You know after summer and so forth... :)

What kind of "hardware" are you running it on?

--
Kind Regards Falk

**Comment by falkowich** [comment]
Hi,

I got the a 100% cpu spike after restart today at work..
![SCAP_100percentCPU](https://user-images.githubusercontent.com/1552705/65424581-2e57f180-de0c-11e9-9478-1d28fecd9de2.png)

Going to check this out more, seems like SCAP is hanging loose..

**Comment by falkowich** [comment]
In this thread there is a good explanation why this happens.

https://community.greenbone.net/t/gvmd-8-scap-update-takes-a-looong-time/3302/6

This is an expected behaviour with xsltproc.

--
Regards Falk
