### ISSUE TITLE
New Alerts - Master GSA - PSQL-Latest

### ISSUE THREAD

**Issue by samredinet** [falkowich/gvm10-docker#21]
Master Docker image
PSQL-Latest 

Built and all working well apart from trying to create a new alert
Error below:
TypeError: Unable to get property 'startsWith' of undefined or null reference

    in Unknown
    in Unknown
    in Unknown
    in div
    in Unknown
    in Layout
    in div
    in styled.div
    in div
    in Unknown
    in Layout
    in Styled(Layout)
    in Unknown
    in t
    in div
    in styled.div
    in t
    in t
    in div
    in styled.div
    in DialogContainer
    in div
    in styled.div
    in t
    in t
    in Unknown
    in t
    in Unknown
    in div
    in Unknown
    in Layout
    in t
    in O
    in Unknown
    in t
    in O
    in Unknown
    in Unknown
    in a
    in O
    in t
    in Unknown
    in O
    in Unknown
    in a
    in t
    in Unknown
    in t
    in t
    in t
    in main
    in Main
    in Unknown
    in withLayout(Main)
    in div
    in Unknown
    in Layout
    in Styled(Layout)
    in t
    in Unknown
    in t
    in O
    in t
    in withRouter(Connect(t))
    in Unknown
    in t
    in O
    in t
    in withRouter(Connect(t))
    in Unknown
    in t
    in t
    in Unknown
    in Unknown
    in t
    in O
    in t
    in t
    in t
TypeError: Unable to get property 'startsWith' of undefined or null reference

Any advise?

**Comment by falkowich** [comment]
Hi,

Latest is in a constant evolving state.
It fetches the latest 10.0 upstream when compiled.

If possible, my recommendation is to stick to stable.

--
Regards Falk

**Comment by samredinet** [comment]
Hi Falk,

I had to move to PSQL-Latest as there is an issue with the stable one in regards to a mis-typed line in manage-sql.c

Whats the best way to update my docker image, just doing another docker pull?

Thanks
Sam

**Comment by samredinet** [comment]
Stable Release has no issues. Reverted back
