### ISSUE TITLE
PDF Report Download - Unable to open

### ISSUE THREAD

**Issue by samredinet** [falkowich/gvm10-docker#23]
Downloading PDF reports - Fail to open.

Known issue that I have come across before. 

![image](https://user-images.githubusercontent.com/50487351/68112070-73ca0d00-fee8-11e9-8bc8-2f19fd695267.png)

Need the following packages added:
texlive-fonts-*
texlive-latex-*

Can you let me know when you can get these into the stable build?

Cheers
Sam

**Comment by samredinet** [comment]
Tested and working

Run the following commands 

apt-get update
apt-get install texlive-fonts-*
apt-get install texlive-latex-*

Working report as shown below after changes!

![image](https://user-images.githubusercontent.com/50487351/68140773-4733e680-ff24-11e9-80fe-590c7364d8d2.png)

**Comment by falkowich** [comment]
Started a buld on:
* stable-psql-test
* stable-sqlite-test
* stable-slave-test

where your proposed fixes are incorporated

--
Regards Falk

**Comment by samredinet** [comment]
Confirmed that PDF generation now works on the following images

- stable-psql-test
- stable-sqlite-test

**Comment by falkowich** [comment]
Merged the changes in stable.
